//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Genesyslab.Desktop.Modules.InteractionExtensionCrossnet.WS_nombre {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WS_nombre.EnviarNombreSoap")]
    public interface EnviarNombreSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento rut del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/envioNombre", ReplyAction="*")]
        Genesyslab.Desktop.Modules.InteractionExtensionCrossnet.WS_nombre.envioNombreResponse envioNombre(Genesyslab.Desktop.Modules.InteractionExtensionCrossnet.WS_nombre.envioNombreRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/envioNombre", ReplyAction="*")]
        System.Threading.Tasks.Task<Genesyslab.Desktop.Modules.InteractionExtensionCrossnet.WS_nombre.envioNombreResponse> envioNombreAsync(Genesyslab.Desktop.Modules.InteractionExtensionCrossnet.WS_nombre.envioNombreRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class envioNombreRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="envioNombre", Namespace="http://tempuri.org/", Order=0)]
        public Genesyslab.Desktop.Modules.InteractionExtensionCrossnet.WS_nombre.envioNombreRequestBody Body;
        
        public envioNombreRequest() {
        }
        
        public envioNombreRequest(Genesyslab.Desktop.Modules.InteractionExtensionCrossnet.WS_nombre.envioNombreRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class envioNombreRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string rut;
        
        public envioNombreRequestBody() {
        }
        
        public envioNombreRequestBody(string rut) {
            this.rut = rut;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class envioNombreResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="envioNombreResponse", Namespace="http://tempuri.org/", Order=0)]
        public Genesyslab.Desktop.Modules.InteractionExtensionCrossnet.WS_nombre.envioNombreResponseBody Body;
        
        public envioNombreResponse() {
        }
        
        public envioNombreResponse(Genesyslab.Desktop.Modules.InteractionExtensionCrossnet.WS_nombre.envioNombreResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class envioNombreResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string envioNombreResult;
        
        public envioNombreResponseBody() {
        }
        
        public envioNombreResponseBody(string envioNombreResult) {
            this.envioNombreResult = envioNombreResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EnviarNombreSoapChannel : Genesyslab.Desktop.Modules.InteractionExtensionCrossnet.WS_nombre.EnviarNombreSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EnviarNombreSoapClient : System.ServiceModel.ClientBase<Genesyslab.Desktop.Modules.InteractionExtensionCrossnet.WS_nombre.EnviarNombreSoap>, Genesyslab.Desktop.Modules.InteractionExtensionCrossnet.WS_nombre.EnviarNombreSoap {
        
        public EnviarNombreSoapClient() {
        }
        
        public EnviarNombreSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EnviarNombreSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EnviarNombreSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EnviarNombreSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Genesyslab.Desktop.Modules.InteractionExtensionCrossnet.WS_nombre.envioNombreResponse Genesyslab.Desktop.Modules.InteractionExtensionCrossnet.WS_nombre.EnviarNombreSoap.envioNombre(Genesyslab.Desktop.Modules.InteractionExtensionCrossnet.WS_nombre.envioNombreRequest request) {
            return base.Channel.envioNombre(request);
        }
        
        public string envioNombre(string rut) {
            Genesyslab.Desktop.Modules.InteractionExtensionCrossnet.WS_nombre.envioNombreRequest inValue = new Genesyslab.Desktop.Modules.InteractionExtensionCrossnet.WS_nombre.envioNombreRequest();
            inValue.Body = new Genesyslab.Desktop.Modules.InteractionExtensionCrossnet.WS_nombre.envioNombreRequestBody();
            inValue.Body.rut = rut;
            Genesyslab.Desktop.Modules.InteractionExtensionCrossnet.WS_nombre.envioNombreResponse retVal = ((Genesyslab.Desktop.Modules.InteractionExtensionCrossnet.WS_nombre.EnviarNombreSoap)(this)).envioNombre(inValue);
            return retVal.Body.envioNombreResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Genesyslab.Desktop.Modules.InteractionExtensionCrossnet.WS_nombre.envioNombreResponse> Genesyslab.Desktop.Modules.InteractionExtensionCrossnet.WS_nombre.EnviarNombreSoap.envioNombreAsync(Genesyslab.Desktop.Modules.InteractionExtensionCrossnet.WS_nombre.envioNombreRequest request) {
            return base.Channel.envioNombreAsync(request);
        }
        
        public System.Threading.Tasks.Task<Genesyslab.Desktop.Modules.InteractionExtensionCrossnet.WS_nombre.envioNombreResponse> envioNombreAsync(string rut) {
            Genesyslab.Desktop.Modules.InteractionExtensionCrossnet.WS_nombre.envioNombreRequest inValue = new Genesyslab.Desktop.Modules.InteractionExtensionCrossnet.WS_nombre.envioNombreRequest();
            inValue.Body = new Genesyslab.Desktop.Modules.InteractionExtensionCrossnet.WS_nombre.envioNombreRequestBody();
            inValue.Body.rut = rut;
            return ((Genesyslab.Desktop.Modules.InteractionExtensionCrossnet.WS_nombre.EnviarNombreSoap)(this)).envioNombreAsync(inValue);
        }
    }
}
