#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Genesyslab.Desktop.Modules.InteractionExtensionCrossnet.Database
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="CN_WORKSPACE_MAIN")]
	public partial class ModeloClasesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    #endregion
		
		public ModeloClasesDataContext() : 
				base(global::Genesyslab.Desktop.Modules.InteractionExtensionCrossnet.Properties.Settings.Default.CN_WORKSPACE_MAINConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ModeloClasesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ModeloClasesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ModeloClasesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ModeloClasesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="wde.SXXX_TRAE_ARBOL_DE_TIPIFICACION")]
		public ISingleResult<SXXX_TRAE_ARBOL_DE_TIPIFICACIONResult> SXXX_TRAE_ARBOL_DE_TIPIFICACION()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SXXX_TRAE_ARBOL_DE_TIPIFICACIONResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="wde.SXXX_TRAE_HISTORIAL")]
		public ISingleResult<SXXX_TRAE_HISTORIALResult> SXXX_TRAE_HISTORIAL([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ANI", DbType="VarChar(30)")] string aNI, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DNIS", DbType="VarChar(30)")] string dNIS, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TIPO", DbType="VarChar(10)")] string tIPO)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), aNI, dNIS, tIPO);
			return ((ISingleResult<SXXX_TRAE_HISTORIALResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="wde.XIUD_INSERTA_TIPIFICACION")]
		public ISingleResult<XIUD_INSERTA_TIPIFICACIONResult> XIUD_INSERTA_TIPIFICACION([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string tipificacion_connid, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string username_agente, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(500)")] string tipificacion_motivo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(250)")] string tipificacion_Observaciones, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string estado_tipificacion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string campana, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDS", DbType="VarChar(MAX)")] string iDS, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> output)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tipificacion_connid, username_agente, tipificacion_motivo, tipificacion_Observaciones, estado_tipificacion, campana, iDS, output);
			output = ((System.Nullable<int>)(result.GetParameterValue(7)));
			return ((ISingleResult<XIUD_INSERTA_TIPIFICACIONResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="wde.XXUI_INSERTA_CAMPANA")]
		public ISingleResult<XXUI_INSERTA_CAMPANAResult> XXUI_INSERTA_CAMPANA(
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="FIRST_NAME", DbType="VarChar(100)")] string fIRST_NAME, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="LAST_NAME", DbType="VarChar(100)")] string lAST_NAME, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="USERNAME", DbType="VarChar(100)")] string uSERNAME, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string tipificacion_connid, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string tipificacion_ani, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string tipificacion_denis, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> tipificacion_tipoInteraccion, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(500)")] string tipificacion_motivo, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(250)")] string tipificacion_Observaciones, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string estado_interaccion, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string estado_tipificacion, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="GUID", DbType="VarChar(50)")] string gUID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CAMPAING_NAME", DbType="VarChar(200)")] string cAMPAING_NAME, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="FIELD", DbType="Xml")] System.Xml.Linq.XElement fIELD, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EVENTO", DbType="VarChar(20)")] string eVENTO, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> output)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), fIRST_NAME, lAST_NAME, uSERNAME, tipificacion_connid, tipificacion_ani, tipificacion_denis, tipificacion_tipoInteraccion, tipificacion_motivo, tipificacion_Observaciones, estado_interaccion, estado_tipificacion, gUID, cAMPAING_NAME, fIELD, eVENTO, output);
			output = ((System.Nullable<int>)(result.GetParameterValue(15)));
			return ((ISingleResult<XXUI_INSERTA_CAMPANAResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="wde.XXUI_INSERTA_INTERACCION_EMAIL")]
		public ISingleResult<XXUI_INSERTA_INTERACCION_EMAILResult> XXUI_INSERTA_INTERACCION_EMAIL([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string interaccionId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string interaccionTipo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string estadoInteraccion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string estadoTipificacion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(MAX)")] string interaccionFrom, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(MAX)")] string interaccionTo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(MAX)")] string interaccionCc, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(MAX)")] string interaccionCco, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string interaccionParentId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> output)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), interaccionId, interaccionTipo, estadoInteraccion, estadoTipificacion, interaccionFrom, interaccionTo, interaccionCc, interaccionCco, interaccionParentId, output);
			output = ((System.Nullable<int>)(result.GetParameterValue(9)));
			return ((ISingleResult<XXUI_INSERTA_INTERACCION_EMAILResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="wde.XXUI_INSERTA_INTERACCION")]
		public ISingleResult<XXUI_INSERTA_INTERACCIONResult> XXUI_INSERTA_INTERACCION(
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="FIRST_NAME", DbType="VarChar(100)")] string fIRST_NAME, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="LAST_NAME", DbType="VarChar(100)")] string lAST_NAME, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="USERNAME", DbType="VarChar(100)")] string uSERNAME, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string tipificacion_connid, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string tipificacion_ani, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string tipificacion_denis, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> tipificacion_tipoInteraccion, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(500)")] string tipificacion_motivo, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(250)")] string tipificacion_Observaciones, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string estado_interaccion, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string estado_tipificacion, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string estado_area, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="1_CANAL", DbType="VarChar(50)")] string _1_CANAL, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="1_OPCION", DbType="VarChar(50)")] string _1_OPCION, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="1_RUT", DbType="VarChar(50)")] string _1_RUT, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="GUID", DbType="VarChar(50)")] string gUID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EVENTO", DbType="VarChar(20)")] string eVENTO, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> output)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), fIRST_NAME, lAST_NAME, uSERNAME, tipificacion_connid, tipificacion_ani, tipificacion_denis, tipificacion_tipoInteraccion, tipificacion_motivo, tipificacion_Observaciones, estado_interaccion, estado_tipificacion, estado_area, _1_CANAL, _1_OPCION, _1_RUT, gUID, eVENTO, output);
			output = ((System.Nullable<int>)(result.GetParameterValue(17)));
			return ((ISingleResult<XXUI_INSERTA_INTERACCIONResult>)(result.ReturnValue));
		}
	}
	
	public partial class SXXX_TRAE_ARBOL_DE_TIPIFICACIONResult
	{
		
		private int _DICCIONARIO_ID;
		
		private string _DESCRIPCION;
		
		private string _VISTA;
		
		private int _DEPENDIENTE;
		
		private bool _ACTIVO;
		
		private string _JERARQUIA;
		
		private int _NIVEL;
		
		private System.Nullable<int> _TIPO_DATO;
		
		public SXXX_TRAE_ARBOL_DE_TIPIFICACIONResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DICCIONARIO_ID", DbType="Int NOT NULL")]
		public int DICCIONARIO_ID
		{
			get
			{
				return this._DICCIONARIO_ID;
			}
			set
			{
				if ((this._DICCIONARIO_ID != value))
				{
					this._DICCIONARIO_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIPCION", DbType="VarChar(80)")]
		public string DESCRIPCION
		{
			get
			{
				return this._DESCRIPCION;
			}
			set
			{
				if ((this._DESCRIPCION != value))
				{
					this._DESCRIPCION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VISTA", DbType="VarChar(30)")]
		public string VISTA
		{
			get
			{
				return this._VISTA;
			}
			set
			{
				if ((this._VISTA != value))
				{
					this._VISTA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPENDIENTE", DbType="Int NOT NULL")]
		public int DEPENDIENTE
		{
			get
			{
				return this._DEPENDIENTE;
			}
			set
			{
				if ((this._DEPENDIENTE != value))
				{
					this._DEPENDIENTE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACTIVO", DbType="Bit NOT NULL")]
		public bool ACTIVO
		{
			get
			{
				return this._ACTIVO;
			}
			set
			{
				if ((this._ACTIVO != value))
				{
					this._ACTIVO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JERARQUIA", DbType="VarChar(50)")]
		public string JERARQUIA
		{
			get
			{
				return this._JERARQUIA;
			}
			set
			{
				if ((this._JERARQUIA != value))
				{
					this._JERARQUIA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NIVEL", DbType="Int NOT NULL")]
		public int NIVEL
		{
			get
			{
				return this._NIVEL;
			}
			set
			{
				if ((this._NIVEL != value))
				{
					this._NIVEL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIPO_DATO", DbType="Int")]
		public System.Nullable<int> TIPO_DATO
		{
			get
			{
				return this._TIPO_DATO;
			}
			set
			{
				if ((this._TIPO_DATO != value))
				{
					this._TIPO_DATO = value;
				}
			}
		}
	}
	
	public partial class SXXX_TRAE_HISTORIALResult
	{
		
		private int _INTERACCION_ID;
		
		private System.Nullable<System.DateTime> _FECHA_HORA_INGRESO;
		
		private string _ANI;
		
		private string @__1_OPCION;
		
		private string _USERNAME;
		
		private string _MOTIVO;
		
		private string _OBSERVACIONES;
		
		private string _TIPO;
		
		public SXXX_TRAE_HISTORIALResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INTERACCION_ID", DbType="Int NOT NULL")]
		public int INTERACCION_ID
		{
			get
			{
				return this._INTERACCION_ID;
			}
			set
			{
				if ((this._INTERACCION_ID != value))
				{
					this._INTERACCION_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_HORA_INGRESO", DbType="DateTime")]
		public System.Nullable<System.DateTime> FECHA_HORA_INGRESO
		{
			get
			{
				return this._FECHA_HORA_INGRESO;
			}
			set
			{
				if ((this._FECHA_HORA_INGRESO != value))
				{
					this._FECHA_HORA_INGRESO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ANI", DbType="VarChar(50)")]
		public string ANI
		{
			get
			{
				return this._ANI;
			}
			set
			{
				if ((this._ANI != value))
				{
					this._ANI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1-OPCION]", Storage="__1_OPCION", DbType="VarChar(50)")]
		public string _1_OPCION
		{
			get
			{
				return this.@__1_OPCION;
			}
			set
			{
				if ((this.@__1_OPCION != value))
				{
					this.@__1_OPCION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USERNAME", DbType="VarChar(100)")]
		public string USERNAME
		{
			get
			{
				return this._USERNAME;
			}
			set
			{
				if ((this._USERNAME != value))
				{
					this._USERNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MOTIVO", DbType="VarChar(500)")]
		public string MOTIVO
		{
			get
			{
				return this._MOTIVO;
			}
			set
			{
				if ((this._MOTIVO != value))
				{
					this._MOTIVO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OBSERVACIONES", DbType="VarChar(250)")]
		public string OBSERVACIONES
		{
			get
			{
				return this._OBSERVACIONES;
			}
			set
			{
				if ((this._OBSERVACIONES != value))
				{
					this._OBSERVACIONES = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIPO", DbType="VarChar(100)")]
		public string TIPO
		{
			get
			{
				return this._TIPO;
			}
			set
			{
				if ((this._TIPO != value))
				{
					this._TIPO = value;
				}
			}
		}
	}
	
	public partial class XIUD_INSERTA_TIPIFICACIONResult
	{
		
		private System.Nullable<int> _ErrorNumber;
		
		private System.Nullable<int> _ErrorSeverity;
		
		private System.Nullable<int> _ErrorState;
		
		private string _ErrorProcedure;
		
		private System.Nullable<int> _ErrorLine;
		
		private string _ErrorMessage;
		
		public XIUD_INSERTA_TIPIFICACIONResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ErrorNumber", DbType="Int")]
		public System.Nullable<int> ErrorNumber
		{
			get
			{
				return this._ErrorNumber;
			}
			set
			{
				if ((this._ErrorNumber != value))
				{
					this._ErrorNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ErrorSeverity", DbType="Int")]
		public System.Nullable<int> ErrorSeverity
		{
			get
			{
				return this._ErrorSeverity;
			}
			set
			{
				if ((this._ErrorSeverity != value))
				{
					this._ErrorSeverity = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ErrorState", DbType="Int")]
		public System.Nullable<int> ErrorState
		{
			get
			{
				return this._ErrorState;
			}
			set
			{
				if ((this._ErrorState != value))
				{
					this._ErrorState = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ErrorProcedure", DbType="NVarChar(128)")]
		public string ErrorProcedure
		{
			get
			{
				return this._ErrorProcedure;
			}
			set
			{
				if ((this._ErrorProcedure != value))
				{
					this._ErrorProcedure = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ErrorLine", DbType="Int")]
		public System.Nullable<int> ErrorLine
		{
			get
			{
				return this._ErrorLine;
			}
			set
			{
				if ((this._ErrorLine != value))
				{
					this._ErrorLine = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ErrorMessage", DbType="NVarChar(4000)")]
		public string ErrorMessage
		{
			get
			{
				return this._ErrorMessage;
			}
			set
			{
				if ((this._ErrorMessage != value))
				{
					this._ErrorMessage = value;
				}
			}
		}
	}
	
	public partial class XXUI_INSERTA_CAMPANAResult
	{
		
		private System.Nullable<int> _ErrorNumber;
		
		private System.Nullable<int> _ErrorSeverity;
		
		private System.Nullable<int> _ErrorState;
		
		private string _ErrorProcedure;
		
		private System.Nullable<int> _ErrorLine;
		
		private string _ErrorMessage;
		
		public XXUI_INSERTA_CAMPANAResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ErrorNumber", DbType="Int")]
		public System.Nullable<int> ErrorNumber
		{
			get
			{
				return this._ErrorNumber;
			}
			set
			{
				if ((this._ErrorNumber != value))
				{
					this._ErrorNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ErrorSeverity", DbType="Int")]
		public System.Nullable<int> ErrorSeverity
		{
			get
			{
				return this._ErrorSeverity;
			}
			set
			{
				if ((this._ErrorSeverity != value))
				{
					this._ErrorSeverity = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ErrorState", DbType="Int")]
		public System.Nullable<int> ErrorState
		{
			get
			{
				return this._ErrorState;
			}
			set
			{
				if ((this._ErrorState != value))
				{
					this._ErrorState = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ErrorProcedure", DbType="NVarChar(128)")]
		public string ErrorProcedure
		{
			get
			{
				return this._ErrorProcedure;
			}
			set
			{
				if ((this._ErrorProcedure != value))
				{
					this._ErrorProcedure = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ErrorLine", DbType="Int")]
		public System.Nullable<int> ErrorLine
		{
			get
			{
				return this._ErrorLine;
			}
			set
			{
				if ((this._ErrorLine != value))
				{
					this._ErrorLine = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ErrorMessage", DbType="NVarChar(4000)")]
		public string ErrorMessage
		{
			get
			{
				return this._ErrorMessage;
			}
			set
			{
				if ((this._ErrorMessage != value))
				{
					this._ErrorMessage = value;
				}
			}
		}
	}
	
	public partial class XXUI_INSERTA_INTERACCION_EMAILResult
	{
		
		private System.Nullable<int> _ErrorNumber;
		
		private System.Nullable<int> _ErrorSeverity;
		
		private System.Nullable<int> _ErrorState;
		
		private string _ErrorProcedure;
		
		private System.Nullable<int> _ErrorLine;
		
		private string _ErrorMessage;
		
		public XXUI_INSERTA_INTERACCION_EMAILResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ErrorNumber", DbType="Int")]
		public System.Nullable<int> ErrorNumber
		{
			get
			{
				return this._ErrorNumber;
			}
			set
			{
				if ((this._ErrorNumber != value))
				{
					this._ErrorNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ErrorSeverity", DbType="Int")]
		public System.Nullable<int> ErrorSeverity
		{
			get
			{
				return this._ErrorSeverity;
			}
			set
			{
				if ((this._ErrorSeverity != value))
				{
					this._ErrorSeverity = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ErrorState", DbType="Int")]
		public System.Nullable<int> ErrorState
		{
			get
			{
				return this._ErrorState;
			}
			set
			{
				if ((this._ErrorState != value))
				{
					this._ErrorState = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ErrorProcedure", DbType="NVarChar(128)")]
		public string ErrorProcedure
		{
			get
			{
				return this._ErrorProcedure;
			}
			set
			{
				if ((this._ErrorProcedure != value))
				{
					this._ErrorProcedure = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ErrorLine", DbType="Int")]
		public System.Nullable<int> ErrorLine
		{
			get
			{
				return this._ErrorLine;
			}
			set
			{
				if ((this._ErrorLine != value))
				{
					this._ErrorLine = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ErrorMessage", DbType="NVarChar(4000)")]
		public string ErrorMessage
		{
			get
			{
				return this._ErrorMessage;
			}
			set
			{
				if ((this._ErrorMessage != value))
				{
					this._ErrorMessage = value;
				}
			}
		}
	}
	
	public partial class XXUI_INSERTA_INTERACCIONResult
	{
		
		private System.Nullable<int> _ErrorNumber;
		
		private System.Nullable<int> _ErrorSeverity;
		
		private System.Nullable<int> _ErrorState;
		
		private string _ErrorProcedure;
		
		private System.Nullable<int> _ErrorLine;
		
		private string _ErrorMessage;
		
		public XXUI_INSERTA_INTERACCIONResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ErrorNumber", DbType="Int")]
		public System.Nullable<int> ErrorNumber
		{
			get
			{
				return this._ErrorNumber;
			}
			set
			{
				if ((this._ErrorNumber != value))
				{
					this._ErrorNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ErrorSeverity", DbType="Int")]
		public System.Nullable<int> ErrorSeverity
		{
			get
			{
				return this._ErrorSeverity;
			}
			set
			{
				if ((this._ErrorSeverity != value))
				{
					this._ErrorSeverity = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ErrorState", DbType="Int")]
		public System.Nullable<int> ErrorState
		{
			get
			{
				return this._ErrorState;
			}
			set
			{
				if ((this._ErrorState != value))
				{
					this._ErrorState = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ErrorProcedure", DbType="NVarChar(128)")]
		public string ErrorProcedure
		{
			get
			{
				return this._ErrorProcedure;
			}
			set
			{
				if ((this._ErrorProcedure != value))
				{
					this._ErrorProcedure = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ErrorLine", DbType="Int")]
		public System.Nullable<int> ErrorLine
		{
			get
			{
				return this._ErrorLine;
			}
			set
			{
				if ((this._ErrorLine != value))
				{
					this._ErrorLine = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ErrorMessage", DbType="NVarChar(4000)")]
		public string ErrorMessage
		{
			get
			{
				return this._ErrorMessage;
			}
			set
			{
				if ((this._ErrorMessage != value))
				{
					this._ErrorMessage = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
